### ISSUE TITLE
Add support for Plone 4.2

### ISSUE THREAD

**Issue by jdinuncio** [collective/plone.jsonapi.routes#25]
The interface for batching apparently changed between Plone 4.2 and Plone 4.3. This makes that most plone.jsonapi.routes fail in Plone 4.2. 

One problem is in plone.jsonapi.routes.api:get_batch, when generating the return dictionary, pagesize invokes batch.pagesize, which works for Plone 4.3, but in plone 4.2 should be batch.size. Sometime similar happens in make_next_url and make_prev_url.

**Comment by ramonski** [comment]
Hm, actually I don't know if I want to add support for Plone 4.2 for this version. What I could imagine is to decouple the whole batching mechanism into a component (aka adapter) to support hooking in. So you could probably add an own Plone 4.2 batching adapter for this?

What do you think?

**Comment by jdinuncio** [comment]
That would be wonderful!

Once the batch code has been separated, would you consider to accept a patch to support Plone 4.2?
I know that older versions use to give a lot of troubles, but they also tend to survive in the wild
more than expected.

Thanks again. 

----- Mensaje original -----
De: "ramonski" <notifications@github.com>
Para: "collective/plone.jsonapi.routes" <plone.jsonapi.routes@noreply.github.com>
CC: "jdinunci" <jdinunci@uc.edu.ve>
Enviados: Domingo, 25 de Enero 2015 17:10:23
Asunto: Re: [plone.jsonapi.routes] Add support for Plone 4.2 (#25)

Hm, actually I don't know if I want to add support for Plone 4.2 for this version. What I could imagine is to decouple the whole batching mechanism into a component (aka adapter) to support hooking in. So you could probably add an own Plone 4.2 batching adapter for this?

What do you think?

---

**Comment by ramonski** [comment]
Ok, thats great. You're more than welcome to contribute:)

**Comment by ramonski** [comment]
@jdinuncio: please check out the 0.5 branch to either implement the backwards compatibility in the `IBatch` adapter (`batch.py`) or write a more specific one for Plone 4.2.

It is a simple wrapper which takes the original plone batch object and proxies the needed functionality to the json api.

**Comment by ramonski** [comment]
@jdinuncio: thanks a lot for the pull request. Good work!:)

**Comment by jdinuncio** [comment]
Is there a release date for 0.5? It will help me to be able to easily declare it as a dependency in buildout.

Thanks.

**Comment by ramonski** [comment]
@jdinuncio I'll plan the release for 0.5 in week 9 - I'll submit a new issue for that
