### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by eleddy** [collective/plone.jsonapi.routes#6]
I'm concerned that configure.zcml has no security on it whatsoever and that field checks aren't done for security either. I haven't done a super deep dive on the code but people will change the security of items in which case the fields presented should be security checked. FOr example, I am not 100% sure but I'm guessing that field = obj.getField(key) has no security on it. Some test cases would help confirm this. Generally, some test cases would help point out these holes faster

**Comment by ramonski** [comment]
closed with a8bcbaf
