### ISSUE TITLE
Plone 5 compatibility issue: Cannot find a tool with name 'reference_catalog'

### ISSUE THREAD

**Issue by sunew** [collective/plone.jsonapi.routes#62]
Accessing an object via the get method and uid fails.

http://localhost:8080/site/@@API/plone/api/1.0/get/8e34c2f764cf48108e5524d1bf83a4b2

    {
    _runtime: 0.030236005783081055,
    message: "Cannot find a tool with name 'reference_catalog'. Available tools are: portal_setup portal_actions portal_catalog portal_controlpanel portal_css portal_diff portal_groupdata portal_groups portal_javascripts portal_memberdata portal_membership portal_migration portal_password_reset portal_properties portal_quickinstaller portal_registration portal_skins portal_types portal_uidannotation portal_uidgenerator portal_uidhandler portal_url portal_view_customizations portal_workflow portal_form_controller portal_transforms portal_archivist portal_historiesstorage portal_historyidhandler portal_modifier portal_purgepolicy portal_referencefactories portal_repository portal_registry portal_resources",
    success: false,
    error: "Traceback (most recent call last): File "/work/projects/forsk2/develop/plone.jsonapi.core/src/plone/jsonapi/core/browser/decorators.py", line 18, in decorator return f(*args, **kwargs) File "/work/projects/forsk2/develop/plone.jsonapi.core/src/plone/jsonapi/core/browser/api.py", line 59, in render return self.dispatch() File "/work/projects/forsk2/develop/plone.jsonapi.core/src/plone/jsonapi/core/browser/api.py", line 53, in dispatch return router(self.context, self.request, path) File "/work/projects/forsk2/develop/plone.jsonapi.core/src/plone/jsonapi/core/browser/router.py", line 136, in __call__ return self.view_functions[endpoint](context, request, **values) File "/work/projects/forsk2/develop/plone.jsonapi.routes/src/plone/jsonapi/routes/providers/crud.py", line 23, in get return get_record(uid=uid) File "/work/projects/forsk2/develop/plone.jsonapi.routes/src/plone/jsonapi/routes/api.py", line 49, in get_record obj = get_object_by_uid(uid) File "/work/projects/forsk2/develop/plone.jsonapi.routes/src/plone/jsonapi/routes/api.py", line 945, in get_object_by_uid rc = get_portal_reference_catalog() File "/work/projects/forsk2/develop/plone.jsonapi.routes/src/plone/jsonapi/routes/api.py", line 611, in get_portal_reference_catalog return get_tool("reference_catalog") File "/work/projects/forsk2/develop/plone.jsonapi.routes/src/plone/jsonapi/routes/api.py", line 593, in get_tool return ploneapi.portal.get_tool(name) File "<string>", line 2, in get_tool File "/work/buildout_cache/eggs/plone.api-1.4.7-py2.7.egg/plone/api/validation.py", line 70, in wrapped return f(*args, **kwargs) File "/work/buildout_cache/eggs/plone.api-1.4.7-py2.7.egg/plone/api/portal.py", line 114, in get_tool "{1}".format(name, '\n'.join(tools)) InvalidParameterError: Cannot find a tool with name 'reference_catalog'. Available tools are: portal_setup portal_actions portal_catalog portal_controlpanel portal_css portal_diff portal_groupdata portal_groups portal_javascripts portal_memberdata portal_membership portal_migration portal_password_reset portal_properties portal_quickinstaller portal_registration portal_skins portal_types portal_uidannotation portal_uidgenerator portal_uidhandler portal_url portal_view_customizations portal_workflow portal_form_controller portal_transforms portal_archivist portal_historiesstorage portal_historyidhandler portal_modifier portal_purgepolicy portal_referencefactories portal_repository portal_registry portal_resources "
    }

**Comment by ramonski** [comment]
Thanks for the report! I will have a look on that

**Comment by jdinuncio** [comment]
I send a pull request (https://github.com/collective/plone.jsonapi.routes/pull/79) with a proposed fix. I was unable to test the problem locally, since I'm using Plone 4, though.
