### ISSUE TITLE
error when adding document in folder

### ISSUE THREAD

**Issue by sunew** [collective/plone.jsonapi.routes#64]
message: "Creation of this portal typeis not allowed in this context."

Standard plone 5 site.

In api.py, get_locally_allowed_types:
method = getattr(obj, "getLocallyAllowedTypes", None)

Method becomes None.
dexterity object apparently has no getLocallyAllowedTypes, but an allowedContentTypes method.

Do not why this is the case - the standard behavior  Folder Addable Constrains is still enabled.

**Comment by ramonski** [comment]
Thanks for reporting this issue @sunew!
I already realized that there are some compatibility issues with Plone 5, will have a look at it soon

**Comment by jianaijun** [comment]
refer: https://github.com/collective/plone.jsonapi.routes/pulls

2015-11-17 17:18 GMT+08:00 ramonski <notifications@github.com>:

**Comment by ramonski** [comment]
Not reproducible anymore - closing
