### ISSUE TITLE
AttributeError: subjects

### ISSUE THREAD

**Issue by ramonski** [collective/plone.jsonapi.routes#86]
## Problem

Datamanager for Dexterity content throws an error
## Details

```
line 353, in get return field.get(self.context)
AttributeError: subjects
```

**Comment by ramonski** [comment]
## Analysis

The field is actually a behavior which is accessed differently than a common field.

 ```python
>>> field.interface
<SchemaClass plone.app.dexterity.behaviors.metadata.ICategorization>
>>> field.interface(self.context).subjects
```

## Todo

- [ ] Check how to fetch the value from a behavior correctly

**Comment by sroney5250** [comment]
@ramonski Is this still a bug?  If so, is there a workaround?

**Comment by ramonski** [comment]
@sroney5250 unfortunately this is still a bug, sorry. I have to take care about this soon.

The only suitable workaround is to overwrite the `set` method of the `DexterityDataManager`:
https://github.com/collective/plone.jsonapi.routes/blob/master/src/plone/jsonapi/routes/datamanagers.py#L297

by inheriting from this class and registering a more specific Interface for your content type:
https://github.com/collective/plone.jsonapi.routes/blob/master/src/plone/jsonapi/routes/configure.zcml#L86

**Comment by ramonski** [comment]
@sroney5250 were you able to reproduce this issue?
I wanted to fix it at the moment, but I'm unable to reproduce it.

**Comment by ramonski** [comment]
Working Branch is `issue-86`: https://github.com/collective/plone.jsonapi.routes/tree/issue-86
